### ISSUE TITLE
question in file:neilf_composite

### ISSUE THREAD

**Issue by JiatengLiu** [NJU-3DV/Relightable3DGaussian#19]
The following two lines of code are found in the `gaussian_render/neilf_composite` , could you please explain the meaning of these two lines of code? And which formula it corresponds to in the paper?
```python
pbr = rendered_pbr
rendered_pbr = pbr + (1 - rendered_opacity) * bg_color[:, None, None]
```
And same code in file `gaussian_render/neilf`
```python
rendered_pbr = pbr + (1 - rendered_opacity) * bg_color[:, None, None]
```

**Comment by swapb94** [comment]
@JiatengLiu , were you able to figure this out?
